export const validationMessage = (label?: string) => ({
  200: () => `Proses${label ? ` ${label}` : ''} berhasil`,
  201: () => `${label || 'Data'} berhasil dibuat`,
  402: () => 'Kolom tidak valid',
  400: () => 'Mohon periksa data yang Anda kirim',
  401: () => 'Mohon maaf Anda tidak punya akses',
  404: () => `${label || 'Data'} tidak ditemukan`,
  408: () => 'Mohon periksa koneksi internet Anda!',
  500: () => 'Terjadi kesalahan server. Mohon coba beberapa saat lagi',
  failedCreate: `Gagal membuat ${label || 'form'}. Mohon periksa form Anda.`,
  failedLogin: (method: 'Email' | 'Nomor telepon') => `${method} atau password Anda salah`,
  failedUpdate: `Gagal mengupdate ${label || 'form'}. Mohon periksa form Anda.`,
  unstableNetwork: 'Koneksi internet tidak stabil',
  noNetwork: `Tidak ada koneksi internet`,
  unstableNetworkDesc: `Terjadi kesalahan dengan koneksi internet Anda. Mohon pastikan Anda terkoneksi dengan internet dan reload browser Anda`,
  required: () => `${label} tidak boleh kosong`,
  invalidField: () => `${label} tidak valid`,
  minChar: (length: number) => `${label} harus minimal ${length} karakter`,
  duplicateValue: `${label || 'Nilai ini'} sudah digunakan`,
  updated: `${label || 'Data'} berhasil diupdate`,
  deleted: `${label || 'Data'} berhasil dihapus`,
  min: (min: number) => `Minimal ${label} adalah ${min}`,
  max: (max: number) => `Maksimal ${label} adalah ${max}`,
  saved: `${label || 'Data'} berhasil disimpan`,
  alreadyRegister: `${label || 'Pengguna'} sudah terdaftar. Anda akan diarahkan ke proses login`,
  invalidPassword:
    'Kata sandi minimal 8 karakter, terdiri dari huruf besar, huruf kecil, angka, dan simbol',
  waitingResend: 'Mohon tunggu beberapa saat lagi untuk mengirim ulang OTP',
  notSame: (compare: string) => `${label} tidak sama dengan ${compare}`,
});
