export const validationMessage = (label?: string) => ({
  2000: () => "Proses berhasil",
  2001: () => "Berhasil dibuat",
  4002: () => `Kolom ${label || "tidak valid"}`,
  4000: () => "Harap periksa input Anda",
  4001: () => "Tidak memiliki hak akses",
  4004: () => `${label || "Data"} tidak ditemukan`,
  4008: () => "Harap periksa koneksi internet Anda!",
  5000: () => "Terjadi kesalahan server internal",
  failedCreate: `Gagal membuat ${label || "form"}. Harap periksa form Anda.`,
  failedUpdate: `Gagal mengupdate ${label || "form"}. Harap periksa form Anda.`,
  unstableNetwork: "Koneksi internet tidak stabil",
  noNetwork: "Tidak ada koneksi internet",
  unstableNetworkDesc:
    "Terjadi kesalahan dengan koneksi internet Anda. Harap periksa koneksi internet Anda dan reload browser Anda.",
  required: () => `${label} harus diisi`,
  invalidField: () => `Format ${label} tidak valid`,
  minChar: (length: number) => `${label} minimal ${length} karakter`,
  duplicateValue: `${label || "Nilai ini"} telah digunakan`,
  updated: `${label || "Data"} berhasil diupdate`,
  deleted: `${label || "Data"} berhasil dihapus`,
  min: (min: number) => `Minimal ${label} adalah ${min}`,
  max: (max: number) => `Maksimal ${label} adalah ${max}`,
  notSame: (compare: string) => `${label} tidak sama dengan ${compare}`,
});
